### PR TITLE
Support for all Rollbar options

### PR DESCRIPTION
**Pull request by endorama**
Hello, I was in need of setting more Rollbar configurations than the one included in this component, and I though to rewrite the logic to permit setting all Rollbar options ( future ones too ).

I also rewrote it to use [Rollbar documented options](https://rollbar.com/docs/notifier/rollbar-php/#configuration-reference) ( snake_case instead of CamelCase ), in order to minimize documentation for this components ( as you can refer to available Rollbar documentation ).

As I didn't want to break compatibility with current version configuration, I made the edit backward compatible.

Thank you for your work in maintaining this project!

### CODE REVIEW

**Comment by baibaratsky** [comment]
@endorama Thank you for contribution!

**Comment by endorama** [comment]
@baibaratsky Thank you for merging it! Any planned date for a release?

**Comment by baibaratsky** [comment]
@endorama Already out 😉

**Comment by endorama** [comment]
😱👍👍

Thanks

**Pull request merged**
